version: '3'

volumes:
  database:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data

  
  build:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./build

networks:
  bridge:
  nginx:
    external: true
    name: nginx


services:

  # Database
  db:
    image: postgres:13
    restart: always
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 7hghqrgyFjmNXBHta
    networks:
      - bridge
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  # Server
  server:
    build: server
    container_name: food_server
    restart: on-failure:3
    depends_on:
      - db
    networks:
      - bridge
      - nginx

  # Client
  client:
    build: client
    container_name: food_client
    restart: on-failure:3
    volumes:
      - build:/app/build
    depends_on:
      - server
    networks:
      - nginx
